"use client";

/* eslint-disable @next/next/no-img-element -- thumbnails are generated by the local photo-library importer. */

import {
  useCallback,
  useEffect,
  useMemo,
  useState,
  type Dispatch,
  type PointerEvent,
  type SetStateAction,
} from "react";
import {
  assetToWork,
  autoComposeTemplateWorks,
  formatFocusPosition,
  isPhotoAssetCompatibleWithSlot,
  isWorkCompatibleWithSlot,
  parseFocusPosition,
  parsePhotoLibraryManifest,
  type PhotoAsset,
} from "../photo-library";
import type { SiteContent, Work } from "../site-config";
import { getTemplateCatalogItem } from "../templates/catalog";

type LibraryFilter = "all" | "landscape" | "portrait";
type LibraryState = "loading" | "ready" | "empty" | "error";

const manifestUrl = "/photos/library-manifest.json";
const assetPageSize = 48;

function slotIndexOf(work: Work, fallback: number) {
  return Number.isInteger(work.slotIndex) ? work.slotIndex as number : fallback;
}

function orientationLabel(orientation: PhotoAsset["orientation"]) {
  if (orientation === "portrait") return "竖幅";
  if (orientation === "landscape") return "横幅";
  return "方幅";
}

export default function PhotoLibraryEditor({
  content,
  setContent,
}: {
  content: SiteContent;
  setContent: Dispatch<SetStateAction<SiteContent>>;
}) {
  const [assets, setAssets] = useState<PhotoAsset[]>([]);
  const [libraryState, setLibraryState] = useState<LibraryState>("loading");
  const [libraryMessage, setLibraryMessage] = useState("正在读取本地素材库…");
  const [filter, setFilter] = useState<LibraryFilter>("all");
  const [query, setQuery] = useState("");
  const [assetPage, setAssetPage] = useState(0);
  const [targetSlotState, setTargetSlotState] = useState<{
    templateId: SiteContent["activeTemplate"];
    slotIndex: number;
  } | null>(null);

  const template = getTemplateCatalogItem(content.activeTemplate);
  const targetSlot = targetSlotState?.templateId === content.activeTemplate
    && targetSlotState.slotIndex < template.photoSlots
    ? targetSlotState.slotIndex
    : null;
  const selectedWorks = useMemo(
    () => content.templateWorks[content.activeTemplate] ?? [],
    [content.activeTemplate, content.templateWorks],
  );
  const layoutConfigured = Object.prototype.hasOwnProperty.call(content.templateWorks, content.activeTemplate);

  const selectedBySlot = useMemo(() => {
    const map = new Map<number, Work>();
    selectedWorks.forEach((work, index) => {
      const slotIndex = slotIndexOf(work, index);
      if (slotIndex >= 0 && slotIndex < template.photoSlots && !map.has(slotIndex)) map.set(slotIndex, work);
    });
    return map;
  }, [selectedWorks, template.photoSlots]);

  const selectedAssetSlots = useMemo(() => {
    const map = new Map<string, number>();
    for (const [slotIndex, work] of selectedBySlot) {
      if (work.assetId) map.set(work.assetId, slotIndex);
    }
    return map;
  }, [selectedBySlot]);

  const filteredAssets = useMemo(() => {
    const needle = query.trim().toLowerCase();
    return assets.filter((asset) => {
      const matchesFilter = filter === "all" || asset.orientation === filter;
      const matchesQuery = !needle || asset.id.toLowerCase().includes(needle);
      return matchesFilter && matchesQuery;
    });
  }, [assets, filter, query]);
  const assetPageCount = Math.max(1, Math.ceil(filteredAssets.length / assetPageSize));
  const currentAssetPage = Math.min(assetPage, assetPageCount - 1);
  const pagedAssets = filteredAssets.slice(
    currentAssetPage * assetPageSize,
    (currentAssetPage + 1) * assetPageSize,
  );

  const loadLibrary = useCallback(async () => {
    try {
      const response = await fetch(`${manifestUrl}?t=${Date.now()}`, { cache: "no-store" });
      if (response.status === 404) {
        setAssets([]);
        setAssetPage(0);
        setLibraryState("empty");
        setLibraryMessage("还没有导入照片文件夹。运行下方命令后，点击“重新读取”。");
        return;
      }
      if (!response.ok) throw new Error(`素材库读取失败（${response.status}）`);

      const manifest = parsePhotoLibraryManifest(await response.json());
      if (!manifest) throw new Error("素材库清单格式无效，请重新执行导入命令");

      setAssets(manifest.assets);
      setAssetPage(0);
      setLibraryState(manifest.assets.length > 0 ? "ready" : "empty");
      setLibraryMessage(
        manifest.assets.length > 0
          ? `已载入 ${manifest.assets.length} 张本地素材；原图没有复制进项目。`
          : "导入已完成，但文件夹中没有可用照片。",
      );
    } catch (error) {
      setAssets([]);
      setAssetPage(0);
      setLibraryState("error");
      setLibraryMessage(error instanceof Error ? error.message : "素材库读取失败");
    }
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => void loadLibrary(), 0);
    return () => window.clearTimeout(timer);
  }, [loadLibrary]);

  const refreshLibrary = () => {
    setLibraryState("loading");
    setLibraryMessage("正在重新读取本地素材库…");
    void loadLibrary();
  };

  const updateTemplateWorks = (updater: (works: Work[]) => Work[]) => {
    const templateId = content.activeTemplate;
    setContent((current) => ({
      ...current,
      templateWorks: {
        ...current.templateWorks,
        [templateId]: updater(current.templateWorks[templateId] ?? []),
      },
    }));
  };

  const updateSlot = (slotIndex: number, patch: Partial<Work>) => {
    updateTemplateWorks((works) => works.map((work, index) => (
      slotIndexOf(work, index) === slotIndex ? { ...work, ...patch, slotIndex } : work
    )));
  };

  const chooseTargetSlot = (slotIndex: number | null) => {
    setTargetSlotState(slotIndex === null ? null : { templateId: content.activeTemplate, slotIndex });
  };

  const removeSlot = (slotIndex: number) => {
    updateTemplateWorks((works) => works.filter((work, index) => slotIndexOf(work, index) !== slotIndex));
    if (targetSlot === slotIndex) setTargetSlotState(null);
  };

  const assignAsset = (asset: PhotoAsset) => {
    updateTemplateWorks((works) => {
      const occupied = new Set(works.map((work, index) => slotIndexOf(work, index)));
      const destination = targetSlot ?? template.slotRatios.findIndex((ratio, index) => (
        !occupied.has(index) && isPhotoAssetCompatibleWithSlot(asset, ratio)
      ));
      if (destination < 0 || destination >= template.photoSlots) return works;
      if (!isPhotoAssetCompatibleWithSlot(asset, template.slotRatios[destination])) return works;

      const existing = works.find((work) => work.assetId === asset.id);
      const withoutDuplicateOrDestination = works.filter((work, index) => {
        const workSlot = slotIndexOf(work, index);
        return work.assetId !== asset.id && workSlot !== destination;
      });
      const next = existing
        ? { ...existing, slotIndex: destination }
        : assetToWork(asset, destination);

      return [...withoutDuplicateOrDestination, next].sort((a, b) => slotIndexOf(a, 0) - slotIndexOf(b, 0));
    });
    setTargetSlotState(null);
  };

  const moveSlot = (slotIndex: number, direction: -1 | 1) => {
    const destination = slotIndex + direction;
    if (destination < 0 || destination >= template.photoSlots) return;
    const sourceWork = selectedBySlot.get(slotIndex);
    const destinationWork = selectedBySlot.get(destination);
    if (!sourceWork || !isWorkCompatibleWithSlot(sourceWork, template.slotRatios[destination])) return;
    if (destinationWork && !isWorkCompatibleWithSlot(destinationWork, template.slotRatios[slotIndex])) return;

    updateTemplateWorks((works) => works.map((work, index) => {
      const currentSlot = slotIndexOf(work, index);
      if (currentSlot === slotIndex) return { ...work, slotIndex: destination };
      if (currentSlot === destination) return { ...work, slotIndex };
      return work;
    }).sort((a, b) => slotIndexOf(a, 0) - slotIndexOf(b, 0)));
  };

  const canMoveSlot = (slotIndex: number, direction: -1 | 1) => {
    const destination = slotIndex + direction;
    if (destination < 0 || destination >= template.photoSlots) return false;
    const sourceWork = selectedBySlot.get(slotIndex);
    const destinationWork = selectedBySlot.get(destination);
    return Boolean(
      sourceWork
      && isWorkCompatibleWithSlot(sourceWork, template.slotRatios[destination])
      && (!destinationWork || isWorkCompatibleWithSlot(destinationWork, template.slotRatios[slotIndex])),
    );
  };

  const setFocusFromPointer = (event: PointerEvent<HTMLButtonElement>, slotIndex: number) => {
    const bounds = event.currentTarget.getBoundingClientRect();
    const x = ((event.clientX - bounds.left) / bounds.width) * 100;
    const y = ((event.clientY - bounds.top) / bounds.height) * 100;
    updateSlot(slotIndex, { position: formatFocusPosition(x, y) });
  };

  const autoCompose = () => {
    updateTemplateWorks((works) => autoComposeTemplateWorks(assets, template.slotRatios, works));
    setTargetSlotState(null);
  };

  const resetLayout = () => {
    updateTemplateWorks(() => []);
    setTargetSlotState(null);
  };

  return (
    <section id="library" className="admin-panel admin-panel-wide photo-library-panel">
      <div className="admin-panel-title">
        <div><small>04</small><h2>素材库与模板排版</h2></div>
        <p>素材库可以很大；主页只使用“{template.name}”的 {template.photoSlots} 个固定照片位。</p>
      </div>

      <div className={`library-import-card is-${libraryState}`}>
        <div>
          <strong>本地文件夹 → 三档 WebP → 私有素材库</strong>
          <p>{libraryMessage}</p>
          <code>npm run photos:import -- --source &quot;&lt;照片文件夹&gt;&quot;</code>
          <small>只生成缩略图、卡片图和全屏图；原图、文件夹路径及文件名不会写入网页数据，也不会进入 Git。</small>
        </div>
        <button type="button" onClick={refreshLibrary} disabled={libraryState === "loading"}>
          {libraryState === "loading" ? "读取中…" : "重新读取素材库"}
        </button>
      </div>

      <div className="layout-summary">
        <div>
          <span>ACTIVE TEMPLATE</span>
          <strong>{template.name}</strong>
          <small>{template.photoRatios}</small>
        </div>
        <div>
          <span>LAYOUT STATUS</span>
          <strong>{layoutConfigured ? `${selectedBySlot.size} / ${template.photoSlots} 已排版` : "沿用旧版作品"}</strong>
          <small>{targetSlot === null ? "选择一个槽位可定点替换素材" : `正在为第 ${targetSlot + 1} 个槽位选图`}</small>
        </div>
        <div className="layout-actions">
          <button type="button" className="layout-auto" onClick={autoCompose} disabled={assets.length === 0}>一键智能排版</button>
          <button type="button" onClick={resetLayout}>清空本模板槽位</button>
        </div>
      </div>

      <div className="photo-layout-workspace">
        <div className="template-slot-pane">
          <div className="library-pane-heading">
            <div><strong>固定照片位</strong><small>比例不合适时宁可留白，也不会强行把横图塞进竖框。</small></div>
            <span>{template.photoSlots} SLOTS</span>
          </div>

          <div className="template-slot-grid">
            {template.slotRatios.map((ratio, slotIndex) => {
              const work = selectedBySlot.get(slotIndex);
              const focus = parseFocusPosition(work?.position ?? "50% 50%");
              return (
                <article
                  className={`template-slot-card ${targetSlot === slotIndex ? "is-target" : ""} ${work ? "is-filled" : "is-empty"}`}
                  data-slot-ratio={ratio}
                  data-slot-index={slotIndex}
                  key={`${content.activeTemplate}-${slotIndex}`}
                >
                  <div className="template-slot-head">
                    <span>SLOT {String(slotIndex + 1).padStart(2, "0")}</span>
                    <strong>{ratio}</strong>
                  </div>

                  {work ? (
                    <>
                      <button
                        type="button"
                        className="slot-focus-canvas"
                        style={{ aspectRatio: ratio.replace(":", " / ") }}
                        onPointerDown={(event) => setFocusFromPointer(event, slotIndex)}
                        aria-label={`设置第 ${slotIndex + 1} 张照片的画面焦点`}
                      >
                        <img
                          src={work.preview}
                          width={work.previewWidth}
                          height={work.previewHeight}
                          alt=""
                          loading="lazy"
                          decoding="async"
                          style={{ objectPosition: work.position }}
                        />
                        <span className="focus-crosshair" style={{ left: `${focus.x}%`, top: `${focus.y}%` }} />
                        <small>点击主体设置焦点</small>
                      </button>

                      <div className="slot-fields">
                        <label><span>标题</span><input value={work.title} onChange={(event) => updateSlot(slotIndex, { title: event.target.value })} /></label>
                        <label><span>描述</span><input value={work.subtitle} onChange={(event) => updateSlot(slotIndex, { subtitle: event.target.value })} /></label>
                      </div>

                      <div className="focus-ranges">
                        <label>
                          <span>水平 {Math.round(focus.x)}%</span>
                          <input aria-label={`第 ${slotIndex + 1} 张照片水平焦点`} type="range" min="0" max="100" value={focus.x} onChange={(event) => updateSlot(slotIndex, { position: formatFocusPosition(Number(event.target.value), focus.y) })} />
                        </label>
                        <label>
                          <span>垂直 {Math.round(focus.y)}%</span>
                          <input aria-label={`第 ${slotIndex + 1} 张照片垂直焦点`} type="range" min="0" max="100" value={focus.y} onChange={(event) => updateSlot(slotIndex, { position: formatFocusPosition(focus.x, Number(event.target.value)) })} />
                        </label>
                      </div>

                      <div className="slot-controls">
                        <button type="button" onClick={() => moveSlot(slotIndex, -1)} disabled={!canMoveSlot(slotIndex, -1)} aria-label="与前一个照片位交换">←</button>
                        <button type="button" onClick={() => moveSlot(slotIndex, 1)} disabled={!canMoveSlot(slotIndex, 1)} aria-label="与后一个照片位交换">→</button>
                        <button type="button" className={targetSlot === slotIndex ? "is-active" : ""} onClick={() => chooseTargetSlot(slotIndex)}>替换</button>
                        <label className="slot-lock"><input type="checkbox" checked={Boolean(work.locked)} onChange={(event) => updateSlot(slotIndex, { locked: event.target.checked })} />锁定</label>
                        <button type="button" className="slot-remove" onClick={() => removeSlot(slotIndex)}>移除</button>
                      </div>
                    </>
                  ) : (
                    <button
                      type="button"
                      className="empty-slot-target"
                      style={{ aspectRatio: ratio.replace(":", " / ") }}
                      onClick={() => chooseTargetSlot(slotIndex)}
                    >
                      <span>{targetSlot === slotIndex ? "请从右侧素材库选择照片" : "选择素材"}</span>
                      <small>PHOTO SLOT / {ratio}</small>
                    </button>
                  )}
                </article>
              );
            })}
          </div>
        </div>

        <div className="asset-library-pane">
          <div className="library-pane-heading">
            <div><strong>本地素材库</strong><small>点击素材会放入目标槽位；未指定时填入第一个比例兼容的空位。</small></div>
            <span>{filteredAssets.length} / {assets.length}</span>
          </div>

          <div className="library-toolbar">
            <label className="library-search"><span className="sr-only">按素材编号搜索</span><input type="search" value={query} onChange={(event) => { setQuery(event.target.value); setAssetPage(0); }} placeholder="搜索素材编号…" /></label>
            <div className="library-filters" aria-label="按画幅筛选">
              {(["all", "landscape", "portrait"] as const).map((value) => (
                <button type="button" aria-pressed={filter === value} onClick={() => { setFilter(value); setAssetPage(0); }} key={value}>
                  {value === "all" ? "全部" : value === "landscape" ? "横幅" : "竖幅"}
                </button>
              ))}
            </div>
          </div>

          {filteredAssets.length > 0 ? (
            <>
              <div className="asset-library-grid">
                {pagedAssets.map((asset) => {
                  const selectedSlot = selectedAssetSlots.get(asset.id);
                  const targetCompatible = targetSlot === null
                    || isPhotoAssetCompatibleWithSlot(asset, template.slotRatios[targetSlot]);
                  const hasCompatibleEmptySlot = template.slotRatios.some((ratio, slotIndex) => (
                    !selectedBySlot.has(slotIndex) && isPhotoAssetCompatibleWithSlot(asset, ratio)
                  ));
                  const canPick = targetSlot === null
                    ? selectedSlot === undefined && hasCompatibleEmptySlot
                    : targetCompatible;
                  const pickHint = !targetCompatible
                    ? `与第 ${targetSlot! + 1} 个槽位方向不符`
                    : selectedSlot !== undefined && targetSlot === null
                      ? `已用于第 ${selectedSlot + 1} 个槽位`
                      : asset.id.slice(0, 12).toUpperCase();

                  return (
                    <article className={`asset-library-card ${selectedSlot === undefined ? "" : "is-selected"}`} key={asset.id}>
                      <button
                        type="button"
                        className="asset-pick"
                        onClick={() => assignAsset(asset)}
                        aria-label={`选择素材 ${asset.id}`}
                        title={canPick ? "放入照片位" : pickHint}
                        disabled={!canPick}
                      >
                        <span className="asset-thumb" style={{ aspectRatio: asset.aspectRatio }}>
                          <img
                            src={asset.variants.thumbnail.src}
                            width={asset.variants.thumbnail.width}
                            height={asset.variants.thumbnail.height}
                            alt=""
                            loading="lazy"
                            decoding="async"
                          />
                          {selectedSlot !== undefined && <b>{String(selectedSlot + 1).padStart(2, "0")}</b>}
                        </span>
                        <span className="asset-card-meta">
                          <strong>{orientationLabel(asset.orientation)} · {asset.aspectRatio.toFixed(2)}</strong>
                          <small>{pickHint}</small>
                        </span>
                      </button>
                    </article>
                  );
                })}
              </div>
              {assetPageCount > 1 && (
                <nav className="library-pagination" aria-label="素材库分页">
                  <button type="button" onClick={() => setAssetPage((page) => Math.max(0, page - 1))} disabled={currentAssetPage === 0}>上一页</button>
                  <span>{currentAssetPage + 1} / {assetPageCount}</span>
                  <button type="button" onClick={() => setAssetPage((page) => Math.min(assetPageCount - 1, page + 1))} disabled={currentAssetPage === assetPageCount - 1}>下一页</button>
                </nav>
              )}
            </>
          ) : (
            <div className="library-empty-state" role="status">
              <strong>{assets.length === 0 ? "素材库还是空的" : "没有符合筛选条件的素材"}</strong>
              <p>{assets.length === 0 ? "先运行文件夹导入命令，再重新读取素材库。" : "试试切换画幅或清空搜索词。"}</p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
