export const labDemoSeries = [
  {
    number: "01",
    chapter: "Threshold",
    title: "A figure enters the light",
    subtitle: "Full silhouette / first spatial note",
    note: "Hold the frame long enough for costume shape and negative space to read together.",
  },
  {
    number: "02",
    chapter: "Profile",
    title: "Quiet armor study",
    subtitle: "Portrait crop / material and expression",
    note: "The caption lives outside the face region and remains readable without the image.",
  },
  {
    number: "03",
    chapter: "Gesture",
    title: "Movement across a fixed horizon",
    subtitle: "Landscape frame / controlled action",
    note: "A wider field gives the pose context while the interface stays visually recessive.",
  },
  {
    number: "04",
    chapter: "Detail",
    title: "Small evidence, held close",
    subtitle: "Portrait frame / craft and texture",
    note: "A narrow image slot slows the sequence without adding ornamental controls.",
  },
  {
    number: "05",
    chapter: "Distance",
    title: "The scene opens again",
    subtitle: "Panoramic frame / environmental release",
    note: "The final wide frame restores location and closes the first visual sentence.",
  },
  {
    number: "06",
    chapter: "Echo",
    title: "A second pose answers",
    subtitle: "Landscape frame / paired rhythm",
    note: "Repeated structure is used for comparison, not to simulate a file browser.",
  },
  {
    number: "07",
    chapter: "Interval",
    title: "Color waits at the edge",
    subtitle: "Wide frame / restrained signal",
    note: "Interface color identifies position while the photographic field owns the palette.",
  },
  {
    number: "08",
    chapter: "Return",
    title: "The character leaves a trace",
    subtitle: "Portrait frame / closing register",
    note: "The final entry remains reachable in document order on every viewport.",
  },
  {
    number: "09",
    chapter: "Afterimage",
    title: "The last frame keeps its coordinates",
    subtitle: "Wide frame / atlas conclusion",
    note: "A visible coordinate and deterministic order close the spatial study without randomness.",
  },
] as const;
